export const INTAKE_OPTIONS = {
  SYMPTOMS: [
    "Sore Throat",
    "Cough",
    "Fever",
    "Headache",
    "Congestion",
    "Mucus Production",
    "Shortness of Breath",
    "Nausea",
  ],
  MEDICAL_HISTORY: [
    "Hypertension",
    "Diabetes",
    "Asthma",
    "High Cholesterol",
    "Thyroid Issues",
    "None",
  ],
  SURGICAL_HISTORY: [
    "Appendectomy",
    "Gallbladder Removal",
    "C-Section",
    "Knee Surgery",
    "Tonsillectomy",
    "None",
  ],
  ALLERGIES: [
    "Penicillin",
    "Sulfa",
    "Latex",
    "Peanuts",
    "Shellfish",
    "No Known Allergies",
  ],
  SOCIAL: {
    SMOKING: ["Never", "Former smoker", "Current smoker"],
    ALCOHOL: ["None", "Occasional", "Frequent"],
  },
};

export const SYMPTOM_CATEGORIES = {
  COMMON: [
    "Sore Throat",
    "Cough",
    "Fever",
    "Headache",
    "Congestion",
    "Mucus Production",
    "Sinus Pressure",
    "Chills",
  ],
  GENERAL: [
    "Nausea",
    "Vomiting",
    "Abdominal Pain",
    "Diarrhea",
    "Constipation",
    "Flank Pain",
    "Burning with Urination",
    "Blood in Urine",
    "Pelvic Pain",
  ],
  GENITOURINARY: [
    "Penile Discharge",
    "Penile Lesion",
    "Scrotal Swelling",
    "Scrotal Pain",
    "Vaginal Discharge",
    "Vaginal Bleeding",
    "Vaginal Itching",
    "Vaginal Pain",
    "Vaginal Rash",
    "Genitourinary Rash",
    "Herpes Rash",
    "Warts",
  ],
  OTHERS: [
    "Back Pain",
    "Shortness of Breath",
    "Chest Pains",
    "Leg Swelling",
    "Wound",
    "Rash",
  ],
};
